# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application/gui/SearchResults.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchResults(object):
    def setupUi(self, SearchResults):
        SearchResults.setObjectName("SearchResults")
        SearchResults.setWindowModality(QtCore.Qt.WindowModal)
        SearchResults.resize(752, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchResults.sizePolicy().hasHeightForWidth())
        SearchResults.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SearchResults)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 751, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.results = QtWidgets.QListWidget(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(10, 70, 731, 661))
        self.results.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.results.setObjectName("results")
        SearchResults.setCentralWidget(self.centralwidget)

        self.retranslateUi(SearchResults)
        QtCore.QMetaObject.connectSlotsByName(SearchResults)

    def retranslateUi(self, SearchResults):
        _translate = QtCore.QCoreApplication.translate
        SearchResults.setWindowTitle(_translate("SearchResults", "MainWindow"))
        self.label.setText(_translate("SearchResults", "Результаты поиска по"))
