# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application/gui/SetWallet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetWallet(object):
    def setupUi(self, SetWallet):
        SetWallet.setObjectName("SetWallet")
        SetWallet.setWindowModality(QtCore.Qt.WindowModal)
        SetWallet.resize(561, 142)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SetWallet.sizePolicy().hasHeightForWidth())
        SetWallet.setSizePolicy(sizePolicy)
        SetWallet.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        SetWallet.setWindowTitle("")
        self.buttonBox = QtWidgets.QDialogButtonBox(SetWallet)
        self.buttonBox.setGeometry(QtCore.QRect(250, 100, 301, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.wallet_input = QtWidgets.QLineEdit(SetWallet)
        self.wallet_input.setGeometry(QtCore.QRect(10, 50, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wallet_input.setFont(font)
        self.wallet_input.setObjectName("wallet_input")
        self.label = QtWidgets.QLabel(SetWallet)
        self.label.setGeometry(QtCore.QRect(10, 0, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(SetWallet)
        self.buttonBox.accepted.connect(SetWallet.accept) # type: ignore
        self.buttonBox.rejected.connect(SetWallet.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetWallet)

    def retranslateUi(self, SetWallet):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("SetWallet", "Введите адрес кошелька"))
